/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ManWhereInput } from "./ManWhereInput";
import { Type } from "class-transformer";
import { ManOrderByInput } from "./ManOrderByInput";

@ArgsType()
class ManFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => ManWhereInput,
  })
  @Field(() => ManWhereInput, { nullable: true })
  @Type(() => ManWhereInput)
  where?: ManWhereInput;

  @ApiProperty({
    required: false,
    type: ManOrderByInput,
  })
  @Field(() => ManOrderByInput, { nullable: true })
  @Type(() => ManOrderByInput)
  orderBy?: ManOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { ManFindManyArgs };
