/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { WomanWhereInput } from "./WomanWhereInput";
import { Type } from "class-transformer";
import { WomanOrderByInput } from "./WomanOrderByInput";

@ArgsType()
class WomanFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => WomanWhereInput,
  })
  @Field(() => WomanWhereInput, { nullable: true })
  @Type(() => WomanWhereInput)
  where?: WomanWhereInput;

  @ApiProperty({
    required: false,
    type: WomanOrderByInput,
  })
  @Field(() => WomanOrderByInput, { nullable: true })
  @Type(() => WomanOrderByInput)
  orderBy?: WomanOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { WomanFindManyArgs };
