/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { IsString, IsOptional, ValidateNested, IsInt } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";
import { Type } from "class-transformer";
import { CustomerCreateNestedManyWithoutAddressesInput } from "./CustomerCreateNestedManyWithoutAddressesInput";
@InputType()
class AddressCreateInput {
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: String,
  })
  address_1?: string | null;

  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: String,
  })
  address_2?: string | null;

  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: String,
  })
  city?: string | null;

  @ValidateNested()
  @Type(() => CustomerCreateNestedManyWithoutAddressesInput)
  @IsOptional()
  @Field(() => CustomerCreateNestedManyWithoutAddressesInput, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: () => CustomerCreateNestedManyWithoutAddressesInput,
  })
  customers?: CustomerCreateNestedManyWithoutAddressesInput;

  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: String,
  })
  state?: string | null;

  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: Number,
  })
  zip?: number | null;
}
export { AddressCreateInput };
