/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { AddressWhereUniqueInput } from "../../address/base/AddressWhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
@InputType()
class CustomerWhereInput {
  @ValidateNested()
  @Type(() => AddressWhereUniqueInput)
  @IsOptional()
  @ApiProperty({
    required: false,
    type: () => AddressWhereUniqueInput,
  })
  address?: AddressWhereUniqueInput;

  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  email?: StringNullableFilter;

  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  firstName?: StringNullableFilter;

  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  id?: StringFilter;

  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  lastName?: StringNullableFilter;

  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  phone?: StringNullableFilter;
}
export { CustomerWhereInput };
