/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { IntNullableFilter } from "../../util/IntNullableFilter";
@InputType()
class OrderWhereInput {
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @IsOptional()
  @ApiProperty({
    required: false,
    type: () => CustomerWhereUniqueInput,
  })
  customer?: CustomerWhereUniqueInput;

  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  discount?: FloatNullableFilter;

  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  id?: StringFilter;

  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  product?: ProductWhereUniqueInput;

  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  quantity?: IntNullableFilter;

  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  totalPrice?: IntNullableFilter;
}
export { OrderWhereInput };
