/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ValidateNested, IsOptional, IsNumber, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { CustomerWhereUniqueInput } from "../../customer/base/CustomerWhereUniqueInput";
import { ApiProperty } from "@nestjs/swagger";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
@InputType()
class OrderUpdateInput {
  @ValidateNested()
  @Type(() => CustomerWhereUniqueInput)
  @IsOptional()
  @ApiProperty({
    required: false,
    type: () => CustomerWhereUniqueInput,
  })
  customer?: CustomerWhereUniqueInput | null;

  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: Number,
  })
  discount?: number | null;

  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  product?: ProductWhereUniqueInput | null;

  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: Number,
  })
  quantity?: number | null;

  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  @ApiProperty({
    required: false,
    type: Number,
  })
  totalPrice?: number | null;
}
export { OrderUpdateInput };
